
// Objective-C API for talking to the following Go packages
//
//	github.com/jnglco/JnglMobile/spinner
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Spinner_FRAMEWORK_H__
#define __Spinner_FRAMEWORK_H__

#include "Spinner.objc.h"
#include "Universe.objc.h"

#endif
