all:
	convert jngl_monkey_square.png -resize 1024x1024 icon_1024x1024.png
	convert jngl_monkey_square.png -resize 512x512 icon_512x512.png
	convert jngl_monkey_square.png -resize 180x180 icon_180x180.png
	convert jngl_monkey_square.png -resize 167x167 icon_167x167.png
	convert jngl_monkey_square.png -resize 152x152 icon_152x152.png
	convert jngl_monkey_square.png -resize 120x120 icon_120x120.png
	convert jngl_monkey_square.png -resize 87x87 icon_87x87.png
	convert jngl_monkey_square.png -resize 80x80 icon_80x80.png
	convert jngl_monkey_square.png -resize 76x76 icon_76x76.png
	convert jngl_monkey_square.png -resize 60x60 icon_60x60.png
	convert jngl_monkey_square.png -resize 58x58 icon_58x58.png
	convert jngl_monkey_square.png -resize 40x40 icon_40x40.png
	convert jngl_monkey_square.png -resize 29x29 icon_29x29.png
	convert jngl_monkey_square.png -resize 20x20 icon_20x20.png
